### ISSUE TITLE
Add to f-droid.org repo

### ISSUE THREAD

**Issue by licaon-kter** [m2049r/xmrwallet#974]
trying to develop a recipe but I'm not even sure which commit I need to build

https://github.com/m2049r/xmrwallet/releases/tag/v4.1.5 says commit `989d52b33de200253f1ea3bc2d7d91b8764079fd`

download APK, unpack, `grep revision META-INF/version-control-info.textproto` -> `revision: "b08cd2fd2f18af55b0f1ee5003a88d8e81712e06"`

but https://github.com/m2049r/xmrwallet/commit/b08cd2fd2f18af55b0f1ee5003a88d8e81712e06 -> 404

**Comment by licaon-kter** [comment]
where should I put `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im0yMDQ5ckBtb25lcnVqby5pbyIsInN1YiI6Mjc0NTEsImlhdCI6MTY4OTg2NDk4OSwiZXhwIjoxODQ3NjUyOTg5fQ.y4dUXb6cIWhHBRUdh2U0lb5Gztn_W6SMFqQxXBtdCUM` exactly?

**Comment by licaon-kter** [comment]
draft recipe **metadata/com.m2049r.xmrwallet.yml** only armv8 for now
```
...see below
```

diff log: [mone415_armv8_local2.log.7z.ZIP](https://github.com/user-attachments/files/17919207/mone415_armv8_local2.log.7z.ZIP) _(remove `.ZIP` from name)_

surely I messed some `PATH`, those were a pain :(

/LE: new recipe below

**Comment by licaon-kter** [comment]
I see a bunch of local paths mentioned in the .so, will move the source to match upstream, hopefully that improves it

```
- [F = (lambda at /src/src/common/apply_permutation.h:67
+ [F = (lambda at /home/vagrant/build/com.m2049r.xmrwallet/external-libs/monero/src/common/apply_permutation.h:67
```

**Comment by licaon-kter** [comment]
updated recipe to match same folders:
```
License: Unknown
SourceCode: https://github.com/m2049r/xmrwallet
IssueTracker: https://github.com/m2049r/xmrwallet/issues

RepoType: git
Repo: https://github.com/m2049r/xmrwallet.git
Binaries: https://github.com/m2049r/xmrwallet/releases/download/v4.1.5/monerujo-4x1x5_universal.apk

Builds:
  - versionName: 4.1.5 'Exolix'
    versionCode: 41052
    commit: 989d52b33de200253f1ea3bc2d7d91b8764079fd
    sudo:
      - mkdir -p /src /opt/android/prefix
      - chown -R vagrant /src /opt/android/prefix
      - apt-get update
      - apt-get install -y automake build-essential cmake file libtool libtinfo5 pkg-config
        python-is-python3 yacc libunwind-dev
    gradle:
      - prod
      - mainnet
    output: app/build/outputs/apk/prodMainnet/release/monerujo-*_arm64-v8a.apk
    srclibs:
      - m2049r-monero@release-v0.18.3.4-monerujo
    prebuild:
      - $$NDK$$/build/tools/make_standalone_toolchain.py --arch arm64 --api 21 --install-dir
        $$SDK$$/toolchain --stl=libc++ --force
      - sed -i -e "s/include 'armeabi-v7a', 'arm64-v8a', 'x86_64'/include 'arm64-v8a'/"
        app/build.gradle
      - sed -i -e '/new File("app/,/^    }/d' app/build.gradle
      - mv $$m2049r-monero$$/* /src/
    build:
      - pushd ..
      - export WORKDIR=$$SDK$$
      - export ANDROID_SDK_ROOT=${WORKDIR}/tools
      - export ANDROID_NDK_ROOT=$$NDK$$
      - export TOOLCHAIN_DIR=${WORKDIR}/toolchain
      - export PREFIX=/opt/android/prefix
      - set -x
      - export BOOST_VERSION=1_70_0
      - export BOOST_VERSION_DOT=1.70.0
      - export BOOST_HASH=430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778
      - curl -L -o boost_${BOOST_VERSION}.tar.bz2 https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION_DOT}/sourc
e/boost_${BOOST_VERSION}.tar.bz2
      - echo "${BOOST_HASH}  boost_${BOOST_VERSION}.tar.bz2" | sha256sum -c
      - tar -xvf boost_${BOOST_VERSION}.tar.bz2
      - rm -f boost_${BOOST_VERSION}.tar.bz2
      - pushd boost_${BOOST_VERSION}
      - ./bootstrap.sh --prefix=${PREFIX}
      - popd
      - export HOST_PATH=$PATH
      - export PATH=$TOOLCHAIN_DIR/aarch64-linux-android/bin:$TOOLCHAIN_DIR/bin:$PATH
      - export ICONV_VERSION=1.16
      - export ICONV_HASH=e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
      - curl -O http://ftp.gnu.org/pub/gnu/libiconv/libiconv-${ICONV_VERSION}.tar.gz
      - echo "${ICONV_HASH}  libiconv-${ICONV_VERSION}.tar.gz" | sha256sum -c
      - tar -xzf libiconv-${ICONV_VERSION}.tar.gz
      - rm -f libiconv-${ICONV_VERSION}.tar.gz
      - pushd libiconv-${ICONV_VERSION}
      - CC=clang CXX=clang++ ./configure --build=x86_64-linux-gnu --host=aarch64-linux-android
        --prefix=${PREFIX} --disable-rpath
      - make -j$(nproc)
      - make install
      - popd
      - pushd boost_${BOOST_VERSION}
      - ./b2 --build-type=minimal link=static runtime-link=static --with-chrono --with-date_time
        --with-filesystem --with-program_options --with-regex --with-serialization
        --with-system --with-thread --with-locale --build-dir=android --stagedir=android
        toolset=clang threading=multi threadapi=pthread target-os=android -sICONV_PATH=${PREFIX}
        install -j$(nproc)
      - popd
      - export ZLIB_VERSION=1.3.1
      - export ZLIB_HASH=9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
      - curl -O https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz
      - echo "${ZLIB_HASH}  zlib-${ZLIB_VERSION}.tar.gz" | sha256sum -c
      - tar -xzf zlib-${ZLIB_VERSION}.tar.gz
      - rm zlib-${ZLIB_VERSION}.tar.gz
      - mv zlib-${ZLIB_VERSION} zlib
      - pushd zlib
      - CC=clang CXX=clang++ ./configure --static --prefix=${PREFIX}
      - make -j$(nproc)
      - make install
      - popd
      - export PATH=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:$HOST_PATH
      - export OPENSSL_VERSION=3.0.5
      - export OPENSSL_HASH=aa7d8d9bef71ad6525c55ba11e5f4397889ce49c2c9349dcea6d3e4f0b024a7a
      - curl -LO https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
      - echo "${OPENSSL_HASH}  openssl-${OPENSSL_VERSION}.tar.gz" | sha256sum -c
      - tar -xzf openssl-${OPENSSL_VERSION}.tar.gz
      - rm openssl-${OPENSSL_VERSION}.tar.gz
      - pushd openssl-${OPENSSL_VERSION}
      - ./Configure android-arm64 -D__ANDROID_API__=21 -static no-shared no-tests
        --with-zlib-include=${PREFIX}/include --with-zlib-lib=${PREFIX}/lib --prefix=${PREFIX}
        --openssldir=${PREFIX}
      - make -j$(nproc)
      - make install_sw
      - popd
      - export ZMQ_VERSION=v4.3.2
      - export ZMQ_HASH=a84ffa12b2eb3569ced199660bac5ad128bff1f0
      - git clone https://github.com/zeromq/libzmq.git -b ${ZMQ_VERSION}
      - pushd libzmq
      - ./autogen.sh
      - CC=clang CXX=clang++ ./configure --prefix=${PREFIX} --host=aarch64-linux-android
        --enable-static --disable-shared
      - make -j$(nproc)
      - make install
      - popd
      - export PATH=$TOOLCHAIN_DIR/aarch64-linux-android/bin:$TOOLCHAIN_DIR/bin:$HOST_PATH
      - export SODIUM_VERSION=1.0.18
      - export SODIUM_HASH=4f5e89fa84ce1d178a6765b8b46f2b6f91216677
      - git clone https://github.com/jedisct1/libsodium.git -b ${SODIUM_VERSION}
      - pushd libsodium
      - ./autogen.sh
      - CC=clang CXX=clang++ ./configure --prefix=${PREFIX} --host=aarch64-linux-android
        --enable-static --disable-shared
      - make -j$(nproc)
      - make install
      - popd
      - export PATH=$HOST_PATH:$TOOLCHAIN_DIR/aarch64-linux-android/bin:$TOOLCHAIN_DIR/bin
      - export LIBEXPAT_VERSION=R_2_4_8
      - export LIBEXPAT_HASH=3bab6c09bbe8bf42d84b81563ddbcf4cca4be838
      - git clone https://github.com/libexpat/libexpat.git -b ${LIBEXPAT_VERSION}
      - pushd libexpat/expat
      - ./buildconf.sh
      - CC=clang CXX=clang++ ./configure --prefix=${PREFIX} --host=aarch64-linux-android
        --enable-static --disable-shared
      - make -j$(nproc)
      - make install
      - popd
      - export PATH=$TOOLCHAIN_DIR/aarch64-linux-android/bin:$TOOLCHAIN_DIR/bin:$HOST_PATH
      - export LIBUNBOUND_VERSION=release-1.16.1
      - export LIBUNBOUND_HASH=903538c76e1d8eb30d0814bb55c3ef1ea28164e8
      - git clone https://github.com/NLnetLabs/unbound.git -b ${LIBUNBOUND_VERSION}
      - pushd unbound
      - CC=clang CXX=clang++ ./configure --prefix=${PREFIX} --host=aarch64-linux-android
        --enable-static --disable-shared --disable-flto --with-ssl=${PREFIX} --with-libexpat=${PREFIX}
      - make -j$(nproc)
      - make install
      - popd
      - popd
      - export CMAKE_INCLUDE_PATH="${PREFIX}/include"
      - export CMAKE_LIBRARY_PATH="${PREFIX}/lib"
      - export ANDROID_STANDALONE_TOOLCHAIN_PATH=${TOOLCHAIN_DIR}
      - export USE_SINGLE_BUILDDIR=1
      - export PATH=$HOST_PATH
      - pushd /src
      - make release-static-android-armv8-wallet_api -j$(nproc)
      - popd
      - mkdir -p external-libs/arm64-v8a/monero
      - find /src/build/release -iname "*.a" -exec cp {} external-libs/arm64-v8a/monero
        \;
      - find /src -iname "wallet2_api.h" -exec cp {} app/src/main/cpp \;
      - find ${PREFIX} -iname "*.a" -exec cp {} external-libs/arm64-v8a \;
    ndk: r17c

AllowedAPKSigningKeys: 967ca1930c19f383a43729a059cd21727855f78cd5e0d9882f780189fe1d8cf1

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 4.1.5 'Exolix'
CurrentVersionCode: 41052
```

diff still huge: [mone415_armv8_local_path1.log.7z.ZIP](https://github.com/user-attachments/files/17922869/mone415_armv8_local_path1.log.7z.ZIP) _(remove .ZIP from name)_

I guess we need to wait for https://github.com/m2049r/xmrwallet/commit/b08cd2fd2f18af55b0f1ee5003a88d8e81712e06 to become available?

maybe I've picked up the wrong https://github.com/m2049r/monero/tree/release-v0.18.3.4-monerujo release?

maybe some lib was not built for arm64 by mistake?

etc
